version: "3.9"

services:
  proxy:
    image: haproxy
    ports:
      - target: 80
        published: 80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - servers-network
  node-server:
    image: glusk/hackathon-2021:latest
    ports:
      - target: 8080
        published: 8080
    command: npm run server
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - servers-network
  node-client:
    image: glusk/hackathon-2021:latest
    environment:
      - CS_HOST=3.67.102.97
      - CS_PORT=80
      - CS_PROTOCOL=ws
    command: npm run client
    deploy:
      mode: replicated
      replicas: 6
    networks:
      - clients-network
networks:
  servers-network:
    driver: overlay
  clients-network:
    driver: overlay
