version: "3.9"

services:
  node-server:
    image: glusk/hackathon-2021:latest
    ports:
      - 8080:8080
    command: npm run server
    deploy:
      endpoint_mode: dnsrr
  node-client:
    image: glusk/hackathon-2021:latest
    environment:
      - CS_HOST=172.19.0.8
      - CS_PROTOCOL=wss
    command: npm run client
    deploy:
      mode: replicated
      replicas: 6
